<?xml version='1.0' encoding='UTF-8' standalone='yes'?>
<!DOCTYPE tomtom[
<!ELEMENT tomtom (model, targets, queries, runtime)>
<!ATTLIST tomtom version CDATA #REQUIRED release CDATA #REQUIRED>
<!ELEMENT model (command_line, distance_measure, threshold, background, host, when)>
<!ELEMENT command_line (#PCDATA)>
<!ELEMENT distance_measure EMPTY>
<!ATTLIST distance_measure value (allr|blic1|blic5|ed|kullback|llr1|llr5|pearson|sandelin) #REQUIRED>
<!ELEMENT threshold (#PCDATA)>
<!ATTLIST threshold type (evalue|qvalue) #REQUIRED>
<!ELEMENT background EMPTY>
<!ATTLIST background from (first_target|file) #REQUIRED A CDATA #REQUIRED C CDATA #REQUIRED G CDATA #REQUIRED T CDATA #REQUIRED file CDATA #IMPLIED>
<!ELEMENT host (#PCDATA)>
<!ELEMENT when (#PCDATA)>
<!-- each target is listed in order that the target was specified to the command line
     the motifs are not listed in any particular order -->
<!ELEMENT targets (target_file*)>
<!ELEMENT target_file (motif*)>
<!ATTLIST target_file index CDATA #REQUIRED source CDATA #REQUIRED name CDATA #REQUIRED 
  loaded CDATA #REQUIRED excluded CDATA #REQUIRED last_mod_date CDATA #REQUIRED>
<!-- currently there can only be one query file (but users should not assume this will always be true)
     the query motifs are specified in the order that they appear in the file
     the matches are ordered from best to worst -->
<!ELEMENT queries (query_file*)>
<!ELEMENT query_file (query*)>
<!ATTLIST query_file source CDATA #REQUIRED name CDATA #REQUIRED last_mod_date CDATA #REQUIRED>
<!ELEMENT query (motif,match*)>
<!ELEMENT match EMPTY>
<!ATTLIST match target IDREF #REQUIRED orientation (forward|reverse) "forward" 
  offset CDATA #REQUIRED pvalue CDATA #REQUIRED evalue CDATA #REQUIRED qvalue CDATA #REQUIRED>
<!-- motif contains the probability of each of the nucleotide bases at each position;
     i starts at 1; A, C, G and T are probabilities that sum to 1 -->
<!ELEMENT motif (pos*)>
<!ATTLIST motif id ID #REQUIRED name CDATA #REQUIRED alt CDATA #IMPLIED length CDATA #REQUIRED 
  nsites CDATA #IMPLIED evalue CDATA #IMPLIED url CDATA #IMPLIED>
<!ELEMENT pos EMPTY>
<!ATTLIST pos i CDATA #REQUIRED A CDATA #REQUIRED C CDATA #REQUIRED G CDATA #REQUIRED T CDATA #REQUIRED>
<!ELEMENT runtime EMPTY>
<!ATTLIST runtime cycles CDATA #REQUIRED seconds CDATA #REQUIRED>
]>
<tomtom version="4.9.1" release="Fri Aug 23 16:49:42 2013 +1000">
	<model>
		<command_line>tomtom -oc ./test/ ./Pathways.union-350-xcb01110-meme.txt ./Pathways.union-350-xcb01110-meme.txt</command_line>
		<distance_measure value="pearson"/>
		<threshold type="qvalue">0.5</threshold>
		<background from="first_target" A="0.173" C="0.327" G="0.327" T="0.173"/>
		<host>Tianhe-2-node32</host>
		<when>Mon May 30 20:26:29 2016</when>
	</model>
	<targets>
		<target_file index="1" source="./Pathways.union-350-xcb01110-meme.txt" name="Pathways.union-350-xcb01110-meme.txt" loaded="9" excluded="0" last_mod_date="Sun May  8 11:41:42 2016">
			<motif id="t_1_1" name="1" length="29" nsites="264" evalue="8.0e-104" >
				<pos i="1" A="0.007576" C="0.424242" G="0.515152" T="0.05303"/>
				<pos i="2" A="0.219697" C="0.465909" G="0.314394" T="0"/>
				<pos i="3" A="0.325758" C="0.128788" G="0.011364" T="0.534091"/>
				<pos i="4" A="0" C="0.147727" G="0.825758" T="0.026515"/>
				<pos i="5" A="0.219697" C="0.375" G="0.32197" T="0.083333"/>
				<pos i="6" A="0.276515" C="0.189394" G="0.132576" T="0.401515"/>
				<pos i="7" A="0.022727" C="0.280303" G="0.560606" T="0.136364"/>
				<pos i="8" A="0.079545" C="0.234848" G="0.670455" T="0.015152"/>
				<pos i="9" A="0.340909" C="0.526515" G="0" T="0.132576"/>
				<pos i="10" A="0.155303" C="0.25" G="0.515152" T="0.079545"/>
				<pos i="11" A="0.143939" C="0.405303" G="0.295455" T="0.155303"/>
				<pos i="12" A="0.215909" C="0.162879" G="0" T="0.621212"/>
				<pos i="13" A="0" C="0.17803" G="0.82197" T="0"/>
				<pos i="14" A="0.113636" C="0.386364" G="0.420455" T="0.079545"/>
				<pos i="15" A="0.212121" C="0.30303" G="0.159091" T="0.325758"/>
				<pos i="16" A="0" C="0.549242" G="0.390152" T="0.060606"/>
				<pos i="17" A="0.272727" C="0.204545" G="0.522727" T="0"/>
				<pos i="18" A="0.409091" C="0.344697" G="0.064394" T="0.181818"/>
				<pos i="19" A="0.128788" C="0.443182" G="0.348485" T="0.079545"/>
				<pos i="20" A="0.181818" C="0.231061" G="0.477273" T="0.109848"/>
				<pos i="21" A="0.227273" C="0.280303" G="0.215909" T="0.276515"/>
				<pos i="22" A="0.045455" C="0.454545" G="0.5" T="0"/>
				<pos i="23" A="0.314394" C="0.295455" G="0.257576" T="0.132576"/>
				<pos i="24" A="0.189394" C="0.136364" G="0.090909" T="0.583333"/>
				<pos i="25" A="0" C="0.325758" G="0.674242" T="0"/>
				<pos i="26" A="0.215909" C="0.477273" G="0.231061" T="0.075758"/>
				<pos i="27" A="0.32197" C="0.083333" G="0.018939" T="0.575758"/>
				<pos i="28" A="0.015152" C="0.204545" G="0.647727" T="0.132576"/>
				<pos i="29" A="0.147727" C="0.314394" G="0.530303" T="0.007576"/>
			</motif>
			<motif id="t_1_2" name="2" length="29" nsites="13" evalue="4.5e-065" >
				<pos i="1" A="0" C="0.846154" G="0" T="0.153846"/>
				<pos i="2" A="0" C="0.230769" G="0.769231" T="0"/>
				<pos i="3" A="0.923077" C="0.076923" G="0" T="0"/>
				<pos i="4" A="0.153846" C="0.076923" G="0" T="0.769231"/>
				<pos i="5" A="0.076923" C="0" G="0" T="0.923077"/>
				<pos i="6" A="0" C="1" G="0" T="0"/>
				<pos i="7" A="0.076923" C="0.923077" G="0" T="0"/>
				<pos i="8" A="0" C="1" G="0" T="0"/>
				<pos i="9" A="0.076923" C="0.615385" G="0.307692" T="0"/>
				<pos i="10" A="1" C="0" G="0" T="0"/>
				<pos i="11" A="0.153846" C="0.153846" G="0" T="0.692308"/>
				<pos i="12" A="0" C="0" G="0" T="1"/>
				<pos i="13" A="0" C="0.923077" G="0" T="0.076923"/>
				<pos i="14" A="0.076923" C="0.846154" G="0" T="0.076923"/>
				<pos i="15" A="0" C="1" G="0" T="0"/>
				<pos i="16" A="0" C="0.384615" G="0.461538" T="0.153846"/>
				<pos i="17" A="0.923077" C="0" G="0" T="0.076923"/>
				<pos i="18" A="0.153846" C="0.307692" G="0" T="0.538462"/>
				<pos i="19" A="0" C="0" G="0" T="1"/>
				<pos i="20" A="0" C="1" G="0" T="0"/>
				<pos i="21" A="0" C="0.846154" G="0" T="0.153846"/>
				<pos i="22" A="0" C="1" G="0" T="0"/>
				<pos i="23" A="0.076923" C="0.461538" G="0.307692" T="0.153846"/>
				<pos i="24" A="1" C="0" G="0" T="0"/>
				<pos i="25" A="0.230769" C="0" G="0" T="0.769231"/>
				<pos i="26" A="0" C="0" G="0" T="1"/>
				<pos i="27" A="0" C="1" G="0" T="0"/>
				<pos i="28" A="0" C="0.923077" G="0" T="0.076923"/>
				<pos i="29" A="0" C="1" G="0" T="0"/>
			</motif>
			<motif id="t_1_3" name="3" length="40" nsites="11" evalue="9.2e-050" >
				<pos i="1" A="0.545455" C="0.181818" G="0.181818" T="0.090909"/>
				<pos i="2" A="0.090909" C="0" G="0.909091" T="0"/>
				<pos i="3" A="0" C="0.909091" G="0.090909" T="0"/>
				<pos i="4" A="0.181818" C="0.454545" G="0.272727" T="0.090909"/>
				<pos i="5" A="0.090909" C="0" G="0.909091" T="0"/>
				<pos i="6" A="0.090909" C="0.090909" G="0.727273" T="0.090909"/>
				<pos i="7" A="0.090909" C="0" G="0.909091" T="0"/>
				<pos i="8" A="1" C="0" G="0" T="0"/>
				<pos i="9" A="0.636364" C="0" G="0.181818" T="0.181818"/>
				<pos i="10" A="0" C="0" G="0" T="1"/>
				<pos i="11" A="0.181818" C="0.636364" G="0.181818" T="0"/>
				<pos i="12" A="0" C="0" G="1" T="0"/>
				<pos i="13" A="0.272727" C="0" G="0.636364" T="0.090909"/>
				<pos i="14" A="0" C="0" G="0.909091" T="0.090909"/>
				<pos i="15" A="1" C="0" G="0" T="0"/>
				<pos i="16" A="0.636364" C="0.090909" G="0.090909" T="0.181818"/>
				<pos i="17" A="0" C="0" G="0" T="1"/>
				<pos i="18" A="0.090909" C="0.727273" G="0.181818" T="0"/>
				<pos i="19" A="0.090909" C="0" G="0.909091" T="0"/>
				<pos i="20" A="0.272727" C="0" G="0.727273" T="0"/>
				<pos i="21" A="0" C="0" G="1" T="0"/>
				<pos i="22" A="1" C="0" G="0" T="0"/>
				<pos i="23" A="0.272727" C="0.181818" G="0.090909" T="0.454545"/>
				<pos i="24" A="0" C="0" G="0" T="1"/>
				<pos i="25" A="0.090909" C="0.545455" G="0.181818" T="0.181818"/>
				<pos i="26" A="0.090909" C="0" G="0.909091" T="0"/>
				<pos i="27" A="0.090909" C="0" G="0.909091" T="0"/>
				<pos i="28" A="0" C="0" G="1" T="0"/>
				<pos i="29" A="1" C="0" G="0" T="0"/>
				<pos i="30" A="0.636364" C="0" G="0" T="0.363636"/>
				<pos i="31" A="0" C="0" G="0" T="1"/>
				<pos i="32" A="0" C="0.545455" G="0.272727" T="0.181818"/>
				<pos i="33" A="0" C="0" G="1" T="0"/>
				<pos i="34" A="0" C="0.545455" G="0.090909" T="0.363636"/>
				<pos i="35" A="0.636364" C="0.181818" G="0" T="0.181818"/>
				<pos i="36" A="0.818182" C="0.090909" G="0.090909" T="0"/>
				<pos i="37" A="0.363636" C="0.545455" G="0.090909" T="0"/>
				<pos i="38" A="0.727273" C="0.090909" G="0.090909" T="0.090909"/>
				<pos i="39" A="0.090909" C="0.181818" G="0.636364" T="0.090909"/>
				<pos i="40" A="0" C="0.818182" G="0.090909" T="0.090909"/>
			</motif>
			<motif id="t_1_4" name="4" length="41" nsites="145" evalue="3.1e-064" >
				<pos i="1" A="0.324138" C="0.206897" G="0.213793" T="0.255172"/>
				<pos i="2" A="0" C="0.57931" G="0.413793" T="0.006897"/>
				<pos i="3" A="0.337931" C="0.02069" G="0.489655" T="0.151724"/>
				<pos i="4" A="0.262069" C="0.234483" G="0.151724" T="0.351724"/>
				<pos i="5" A="0" C="0.496552" G="0.482759" T="0.02069"/>
				<pos i="6" A="0.2" C="0.234483" G="0.386207" T="0.17931"/>
				<pos i="7" A="0.2" C="0.206897" G="0.186207" T="0.406897"/>
				<pos i="8" A="0" C="0.613793" G="0.331034" T="0.055172"/>
				<pos i="9" A="0.462069" C="0.075862" G="0.324138" T="0.137931"/>
				<pos i="10" A="0" C="0.4" G="0.2" T="0.4"/>
				<pos i="11" A="0" C="0.77931" G="0.22069" T="0"/>
				<pos i="12" A="0.262069" C="0.075862" G="0.6" T="0.062069"/>
				<pos i="13" A="0.441379" C="0.234483" G="0.144828" T="0.17931"/>
				<pos i="14" A="0.17931" C="0.627586" G="0.110345" T="0.082759"/>
				<pos i="15" A="0.351724" C="0" G="0.468966" T="0.17931"/>
				<pos i="16" A="0.413793" C="0.275862" G="0.213793" T="0.096552"/>
				<pos i="17" A="0.055172" C="0.668966" G="0.151724" T="0.124138"/>
				<pos i="18" A="0.089655" C="0.248276" G="0.558621" T="0.103448"/>
				<pos i="19" A="0.144828" C="0.255172" G="0.331034" T="0.268966"/>
				<pos i="20" A="0" C="0.634483" G="0.344828" T="0.02069"/>
				<pos i="21" A="0.441379" C="0.206897" G="0.310345" T="0.041379"/>
				<pos i="22" A="0.337931" C="0.103448" G="0.124138" T="0.434483"/>
				<pos i="23" A="0.013793" C="0.517241" G="0.358621" T="0.110345"/>
				<pos i="24" A="0.22069" C="0.110345" G="0.586207" T="0.082759"/>
				<pos i="25" A="0.151724" C="0.351724" G="0.365517" T="0.131034"/>
				<pos i="26" A="0.006897" C="0.848276" G="0.075862" T="0.068966"/>
				<pos i="27" A="0.351724" C="0.055172" G="0.462069" T="0.131034"/>
				<pos i="28" A="0.303448" C="0.262069" G="0.275862" T="0.158621"/>
				<pos i="29" A="0.062069" C="0.593103" G="0.213793" T="0.131034"/>
				<pos i="30" A="0.289655" C="0.131034" G="0.455172" T="0.124138"/>
				<pos i="31" A="0.17931" C="0.117241" G="0.4" T="0.303448"/>
				<pos i="32" A="0" C="0.696552" G="0.289655" T="0.013793"/>
				<pos i="33" A="0.275862" C="0.303448" G="0.344828" T="0.075862"/>
				<pos i="34" A="0.303448" C="0.193103" G="0.103448" T="0.4"/>
				<pos i="35" A="0.013793" C="0.241379" G="0.717241" T="0.027586"/>
				<pos i="36" A="0.206897" C="0.282759" G="0.37931" T="0.131034"/>
				<pos i="37" A="0.213793" C="0.241379" G="0.117241" T="0.427586"/>
				<pos i="38" A="0.041379" C="0.448276" G="0.510345" T="0"/>
				<pos i="39" A="0.248276" C="0.289655" G="0.282759" T="0.17931"/>
				<pos i="40" A="0.082759" C="0.082759" G="0.475862" T="0.358621"/>
				<pos i="41" A="0.02069" C="0.744828" G="0.227586" T="0.006897"/>
			</motif>
			<motif id="t_1_5" name="5" length="41" nsites="145" evalue="2.1e-015" >
				<pos i="1" A="0.096552" C="0.655172" G="0.248276" T="0"/>
				<pos i="2" A="0.441379" C="0.068966" G="0" T="0.489655"/>
				<pos i="3" A="0.006897" C="0.158621" G="0.765517" T="0.068966"/>
				<pos i="4" A="0.075862" C="0.365517" G="0.482759" T="0.075862"/>
				<pos i="5" A="0.17931" C="0.393103" G="0.289655" T="0.137931"/>
				<pos i="6" A="0.013793" C="0.572414" G="0.37931" T="0.034483"/>
				<pos i="7" A="0.289655" C="0.310345" G="0.303448" T="0.096552"/>
				<pos i="8" A="0.406897" C="0.006897" G="0.151724" T="0.434483"/>
				<pos i="9" A="0" C="0.406897" G="0.358621" T="0.234483"/>
				<pos i="10" A="0.117241" C="0.22069" G="0.6" T="0.062069"/>
				<pos i="11" A="0.034483" C="0.310345" G="0.496552" T="0.158621"/>
				<pos i="12" A="0" C="0.882759" G="0.117241" T="0"/>
				<pos i="13" A="0.434483" C="0.041379" G="0.386207" T="0.137931"/>
				<pos i="14" A="0.475862" C="0.151724" G="0.110345" T="0.262069"/>
				<pos i="15" A="0.013793" C="0.475862" G="0.255172" T="0.255172"/>
				<pos i="16" A="0.117241" C="0.22069" G="0.62069" T="0.041379"/>
				<pos i="17" A="0.2" C="0.331034" G="0.110345" T="0.358621"/>
				<pos i="18" A="0.068966" C="0.393103" G="0.503448" T="0.034483"/>
				<pos i="19" A="0.110345" C="0.296552" G="0.544828" T="0.048276"/>
				<pos i="20" A="0.262069" C="0.37931" G="0.117241" T="0.241379"/>
				<pos i="21" A="0.068966" C="0.337931" G="0.551724" T="0.041379"/>
				<pos i="22" A="0.089655" C="0.496552" G="0.262069" T="0.151724"/>
				<pos i="23" A="0.324138" C="0.110345" G="0.172414" T="0.393103"/>
				<pos i="24" A="0.027586" C="0.344828" G="0.517241" T="0.110345"/>
				<pos i="25" A="0.158621" C="0.22069" G="0.503448" T="0.117241"/>
				<pos i="26" A="0.289655" C="0.282759" G="0.110345" T="0.317241"/>
				<pos i="27" A="0.110345" C="0.351724" G="0.524138" T="0.013793"/>
				<pos i="28" A="0.089655" C="0.413793" G="0.37931" T="0.117241"/>
				<pos i="29" A="0.42069" C="0.17931" G="0.055172" T="0.344828"/>
				<pos i="30" A="0.075862" C="0.124138" G="0.662069" T="0.137931"/>
				<pos i="31" A="0.186207" C="0.468966" G="0.131034" T="0.213793"/>
				<pos i="32" A="0.268966" C="0.117241" G="0.172414" T="0.441379"/>
				<pos i="33" A="0.013793" C="0.337931" G="0.496552" T="0.151724"/>
				<pos i="34" A="0.041379" C="0.537931" G="0.358621" T="0.062069"/>
				<pos i="35" A="0.131034" C="0.303448" G="0.096552" T="0.468966"/>
				<pos i="36" A="0.006897" C="0.310345" G="0.613793" T="0.068966"/>
				<pos i="37" A="0.075862" C="0.206897" G="0.613793" T="0.103448"/>
				<pos i="38" A="0.434483" C="0.268966" G="0.089655" T="0.206897"/>
				<pos i="39" A="0.117241" C="0.337931" G="0.324138" T="0.22069"/>
				<pos i="40" A="0.137931" C="0.296552" G="0.406897" T="0.158621"/>
				<pos i="41" A="0.262069" C="0.289655" G="0.124138" T="0.324138"/>
			</motif>
			<motif id="t_1_6" name="6" length="21" nsites="31" evalue="2.8e-009" >
				<pos i="1" A="0.322581" C="0.032258" G="0.516129" T="0.129032"/>
				<pos i="2" A="0.032258" C="0.806452" G="0.032258" T="0.129032"/>
				<pos i="3" A="0" C="0.322581" G="0.677419" T="0"/>
				<pos i="4" A="0.032258" C="0.354839" G="0.483871" T="0.129032"/>
				<pos i="5" A="0" C="0.322581" G="0.16129" T="0.516129"/>
				<pos i="6" A="0.064516" C="0" G="0.225806" T="0.709677"/>
				<pos i="7" A="0.032258" C="0.096774" G="0.064516" T="0.806452"/>
				<pos i="8" A="0" C="0.16129" G="0" T="0.83871"/>
				<pos i="9" A="0.032258" C="0" G="0.064516" T="0.903226"/>
				<pos i="10" A="0" C="0" G="0.096774" T="0.903226"/>
				<pos i="11" A="0.032258" C="0.225806" G="0" T="0.741935"/>
				<pos i="12" A="0.258065" C="0.096774" G="0.129032" T="0.516129"/>
				<pos i="13" A="0" C="0" G="0.322581" T="0.677419"/>
				<pos i="14" A="0.032258" C="0.483871" G="0.290323" T="0.193548"/>
				<pos i="15" A="0.193548" C="0" G="0.483871" T="0.322581"/>
				<pos i="16" A="0.032258" C="0.354839" G="0.516129" T="0.096774"/>
				<pos i="17" A="0.096774" C="0.548387" G="0.16129" T="0.193548"/>
				<pos i="18" A="0.290323" C="0.096774" G="0.548387" T="0.064516"/>
				<pos i="19" A="0.451613" C="0.225806" G="0.129032" T="0.193548"/>
				<pos i="20" A="0" C="0.096774" G="0" T="0.903226"/>
				<pos i="21" A="0" C="0.129032" G="0.548387" T="0.322581"/>
			</motif>
			<motif id="t_1_7" name="7" length="41" nsites="8" evalue="6.9e-006" >
				<pos i="1" A="0" C="0" G="1" T="0"/>
				<pos i="2" A="0" C="1" G="0" T="0"/>
				<pos i="3" A="0.125" C="0.625" G="0.25" T="0"/>
				<pos i="4" A="0" C="0" G="0.625" T="0.375"/>
				<pos i="5" A="0" C="0.625" G="0" T="0.375"/>
				<pos i="6" A="0" C="0.875" G="0.125" T="0"/>
				<pos i="7" A="0" C="0" G="1" T="0"/>
				<pos i="8" A="0" C="1" G="0" T="0"/>
				<pos i="9" A="0.375" C="0" G="0.625" T="0"/>
				<pos i="10" A="0.375" C="0.25" G="0" T="0.375"/>
				<pos i="11" A="0" C="0.125" G="0.5" T="0.375"/>
				<pos i="12" A="0.125" C="0.875" G="0" T="0"/>
				<pos i="13" A="0.75" C="0" G="0.25" T="0"/>
				<pos i="14" A="0" C="0.625" G="0.125" T="0.25"/>
				<pos i="15" A="0" C="0.125" G="0.625" T="0.25"/>
				<pos i="16" A="0" C="0.25" G="0.75" T="0"/>
				<pos i="17" A="0" C="1" G="0" T="0"/>
				<pos i="18" A="0.875" C="0" G="0" T="0.125"/>
				<pos i="19" A="0.5" C="0.125" G="0.25" T="0.125"/>
				<pos i="20" A="0.25" C="0.25" G="0.125" T="0.375"/>
				<pos i="21" A="0" C="0.875" G="0.125" T="0"/>
				<pos i="22" A="0.125" C="0" G="0.875" T="0"/>
				<pos i="23" A="0" C="1" G="0" T="0"/>
				<pos i="24" A="0" C="1" G="0" T="0"/>
				<pos i="25" A="0.125" C="0.5" G="0.375" T="0"/>
				<pos i="26" A="0" C="0.75" G="0.25" T="0"/>
				<pos i="27" A="0" C="0.75" G="0.25" T="0"/>
				<pos i="28" A="0.375" C="0.5" G="0.125" T="0"/>
				<pos i="29" A="0.5" C="0" G="0" T="0.5"/>
				<pos i="30" A="0" C="1" G="0" T="0"/>
				<pos i="31" A="0" C="0.375" G="0.625" T="0"/>
				<pos i="32" A="0" C="1" G="0" T="0"/>
				<pos i="33" A="0.875" C="0.125" G="0" T="0"/>
				<pos i="34" A="0.125" C="0.25" G="0.5" T="0.125"/>
				<pos i="35" A="0" C="0.375" G="0" T="0.625"/>
				<pos i="36" A="0.125" C="0.5" G="0.375" T="0"/>
				<pos i="37" A="0.625" C="0" G="0.375" T="0"/>
				<pos i="38" A="0.375" C="0.25" G="0.25" T="0.125"/>
				<pos i="39" A="0" C="0.75" G="0.25" T="0"/>
				<pos i="40" A="0" C="0" G="1" T="0"/>
				<pos i="41" A="0.125" C="0.875" G="0" T="0"/>
			</motif>
			<motif id="t_1_8" name="8" length="15" nsites="27" evalue="9.5e-003" >
				<pos i="1" A="0.555556" C="0.037037" G="0.222222" T="0.185185"/>
				<pos i="2" A="0.074074" C="0.259259" G="0" T="0.666667"/>
				<pos i="3" A="0" C="0.074074" G="0.925926" T="0"/>
				<pos i="4" A="0" C="1" G="0" T="0"/>
				<pos i="5" A="0.407407" C="0.148148" G="0" T="0.444444"/>
				<pos i="6" A="0.111111" C="0" G="0.888889" T="0"/>
				<pos i="7" A="0" C="1" G="0" T="0"/>
				<pos i="8" A="0.518519" C="0" G="0.481481" T="0"/>
				<pos i="9" A="0.111111" C="0.888889" G="0" T="0"/>
				<pos i="10" A="0" C="0.074074" G="0" T="0.925926"/>
				<pos i="11" A="0" C="0" G="0.851852" T="0.148148"/>
				<pos i="12" A="0.037037" C="0.962963" G="0" T="0"/>
				<pos i="13" A="0.481481" C="0.111111" G="0.37037" T="0.037037"/>
				<pos i="14" A="0" C="0.185185" G="0.777778" T="0.037037"/>
				<pos i="15" A="0" C="0.814815" G="0.074074" T="0.111111"/>
			</motif>
			<motif id="t_1_9" name="9" length="49" nsites="26" evalue="6.2e-002" >
				<pos i="1" A="0" C="0.538462" G="0.423077" T="0.038462"/>
				<pos i="2" A="0" C="0.692308" G="0.307692" T="0"/>
				<pos i="3" A="0.461538" C="0" G="0" T="0.538462"/>
				<pos i="4" A="0.076923" C="0.038462" G="0.769231" T="0.115385"/>
				<pos i="5" A="0" C="0.692308" G="0.192308" T="0.115385"/>
				<pos i="6" A="0.192308" C="0.076923" G="0.269231" T="0.461538"/>
				<pos i="7" A="0" C="0.076923" G="0.846154" T="0.076923"/>
				<pos i="8" A="0.076923" C="0.5" G="0.346154" T="0.076923"/>
				<pos i="9" A="0.538462" C="0.192308" G="0.153846" T="0.115385"/>
				<pos i="10" A="0.153846" C="0.192308" G="0.346154" T="0.307692"/>
				<pos i="11" A="0.038462" C="0.153846" G="0.730769" T="0.076923"/>
				<pos i="12" A="0.115385" C="0.423077" G="0.192308" T="0.269231"/>
				<pos i="13" A="0" C="0.807692" G="0.192308" T="0"/>
				<pos i="14" A="0.153846" C="0.076923" G="0.461538" T="0.307692"/>
				<pos i="15" A="0.192308" C="0.115385" G="0.384615" T="0.307692"/>
				<pos i="16" A="0" C="0.576923" G="0" T="0.423077"/>
				<pos i="17" A="0.038462" C="0.153846" G="0.807692" T="0"/>
				<pos i="18" A="0.076923" C="0.192308" G="0.461538" T="0.269231"/>
				<pos i="19" A="0" C="0.884615" G="0.038462" T="0.076923"/>
				<pos i="20" A="0.076923" C="0.076923" G="0.769231" T="0.076923"/>
				<pos i="21" A="0.230769" C="0.346154" G="0.115385" T="0.307692"/>
				<pos i="22" A="0.076923" C="0.5" G="0.192308" T="0.230769"/>
				<pos i="23" A="0.153846" C="0" G="0.807692" T="0.038462"/>
				<pos i="24" A="0.269231" C="0.5" G="0.115385" T="0.115385"/>
				<pos i="25" A="0.153846" C="0.5" G="0.192308" T="0.153846"/>
				<pos i="26" A="0" C="0.192308" G="0.769231" T="0.038462"/>
				<pos i="27" A="0.384615" C="0.423077" G="0.038462" T="0.153846"/>
				<pos i="28" A="0.269231" C="0.384615" G="0.269231" T="0.076923"/>
				<pos i="29" A="0.230769" C="0.192308" G="0.461538" T="0.115385"/>
				<pos i="30" A="0.307692" C="0.153846" G="0.153846" T="0.384615"/>
				<pos i="31" A="0.115385" C="0.230769" G="0.384615" T="0.269231"/>
				<pos i="32" A="0" C="0.538462" G="0.307692" T="0.153846"/>
				<pos i="33" A="0.153846" C="0.384615" G="0.115385" T="0.346154"/>
				<pos i="34" A="0.269231" C="0.269231" G="0.423077" T="0.038462"/>
				<pos i="35" A="0.153846" C="0.384615" G="0.230769" T="0.230769"/>
				<pos i="36" A="0.461538" C="0" G="0.153846" T="0.384615"/>
				<pos i="37" A="0" C="0.307692" G="0.230769" T="0.461538"/>
				<pos i="38" A="0" C="0" G="1" T="0"/>
				<pos i="39" A="0.076923" C="0.615385" G="0.192308" T="0.115385"/>
				<pos i="40" A="0.038462" C="0.230769" G="0.576923" T="0.153846"/>
				<pos i="41" A="0" C="0.653846" G="0.346154" T="0"/>
				<pos i="42" A="0.115385" C="0.153846" G="0.115385" T="0.615385"/>
				<pos i="43" A="0" C="0.115385" G="0.846154" T="0.038462"/>
				<pos i="44" A="0" C="0.384615" G="0.576923" T="0.038462"/>
				<pos i="45" A="0.192308" C="0.115385" G="0.346154" T="0.346154"/>
				<pos i="46" A="0" C="0.807692" G="0.192308" T="0"/>
				<pos i="47" A="0.076923" C="0.038462" G="0.807692" T="0.076923"/>
				<pos i="48" A="0.384615" C="0.384615" G="0.230769" T="0"/>
				<pos i="49" A="0.115385" C="0.538462" G="0.076923" T="0.269231"/>
			</motif>
		</target_file>
	</targets>
	<queries>
		<query_file source="./Pathways.union-350-xcb01110-meme.txt" name="Pathways.union-350-xcb01110-meme.txt" last_mod_date="Sun May  8 11:41:42 2016">
			<query>
				<motif id="q_1" name="1" length="29" nsites="264" evalue="8.0e-104" >
					<pos i="1" A="0.007576" C="0.424242" G="0.515152" T="0.05303"/>
					<pos i="2" A="0.219697" C="0.465909" G="0.314394" T="0"/>
					<pos i="3" A="0.325758" C="0.128788" G="0.011364" T="0.534091"/>
					<pos i="4" A="0" C="0.147727" G="0.825758" T="0.026515"/>
					<pos i="5" A="0.219697" C="0.375" G="0.32197" T="0.083333"/>
					<pos i="6" A="0.276515" C="0.189394" G="0.132576" T="0.401515"/>
					<pos i="7" A="0.022727" C="0.280303" G="0.560606" T="0.136364"/>
					<pos i="8" A="0.079545" C="0.234848" G="0.670455" T="0.015152"/>
					<pos i="9" A="0.340909" C="0.526515" G="0" T="0.132576"/>
					<pos i="10" A="0.155303" C="0.25" G="0.515152" T="0.079545"/>
					<pos i="11" A="0.143939" C="0.405303" G="0.295455" T="0.155303"/>
					<pos i="12" A="0.215909" C="0.162879" G="0" T="0.621212"/>
					<pos i="13" A="0" C="0.17803" G="0.82197" T="0"/>
					<pos i="14" A="0.113636" C="0.386364" G="0.420455" T="0.079545"/>
					<pos i="15" A="0.212121" C="0.30303" G="0.159091" T="0.325758"/>
					<pos i="16" A="0" C="0.549242" G="0.390152" T="0.060606"/>
					<pos i="17" A="0.272727" C="0.204545" G="0.522727" T="0"/>
					<pos i="18" A="0.409091" C="0.344697" G="0.064394" T="0.181818"/>
					<pos i="19" A="0.128788" C="0.443182" G="0.348485" T="0.079545"/>
					<pos i="20" A="0.181818" C="0.231061" G="0.477273" T="0.109848"/>
					<pos i="21" A="0.227273" C="0.280303" G="0.215909" T="0.276515"/>
					<pos i="22" A="0.045455" C="0.454545" G="0.5" T="0"/>
					<pos i="23" A="0.314394" C="0.295455" G="0.257576" T="0.132576"/>
					<pos i="24" A="0.189394" C="0.136364" G="0.090909" T="0.583333"/>
					<pos i="25" A="0" C="0.325758" G="0.674242" T="0"/>
					<pos i="26" A="0.215909" C="0.477273" G="0.231061" T="0.075758"/>
					<pos i="27" A="0.32197" C="0.083333" G="0.018939" T="0.575758"/>
					<pos i="28" A="0.015152" C="0.204545" G="0.647727" T="0.132576"/>
					<pos i="29" A="0.147727" C="0.314394" G="0.530303" T="0.007576"/>
				</motif>
				<match target="t_1_1" orientation="forward" offset="0" pvalue="0" evalue="0" qvalue="0"/>
				<match target="t_1_5" orientation="forward" offset="-4" pvalue="4.05243e-06" evalue="3.64718e-05" qvalue="3.64718e-05"/>
				<match target="t_1_9" orientation="forward" offset="18" pvalue="0.00579704" evalue="0.0521734" qvalue="0.0208693"/>
				<match target="t_1_4" orientation="forward" offset="-5" pvalue="0.0131425" evalue="0.118283" qvalue="0.0394276"/>
			</query>
			<query>
				<motif id="q_2" name="2" length="29" nsites="13" evalue="4.5e-065" >
					<pos i="1" A="0" C="0.846154" G="0" T="0.153846"/>
					<pos i="2" A="0" C="0.230769" G="0.769231" T="0"/>
					<pos i="3" A="0.923077" C="0.076923" G="0" T="0"/>
					<pos i="4" A="0.153846" C="0.076923" G="0" T="0.769231"/>
					<pos i="5" A="0.076923" C="0" G="0" T="0.923077"/>
					<pos i="6" A="0" C="1" G="0" T="0"/>
					<pos i="7" A="0.076923" C="0.923077" G="0" T="0"/>
					<pos i="8" A="0" C="1" G="0" T="0"/>
					<pos i="9" A="0.076923" C="0.615385" G="0.307692" T="0"/>
					<pos i="10" A="1" C="0" G="0" T="0"/>
					<pos i="11" A="0.153846" C="0.153846" G="0" T="0.692308"/>
					<pos i="12" A="0" C="0" G="0" T="1"/>
					<pos i="13" A="0" C="0.923077" G="0" T="0.076923"/>
					<pos i="14" A="0.076923" C="0.846154" G="0" T="0.076923"/>
					<pos i="15" A="0" C="1" G="0" T="0"/>
					<pos i="16" A="0" C="0.384615" G="0.461538" T="0.153846"/>
					<pos i="17" A="0.923077" C="0" G="0" T="0.076923"/>
					<pos i="18" A="0.153846" C="0.307692" G="0" T="0.538462"/>
					<pos i="19" A="0" C="0" G="0" T="1"/>
					<pos i="20" A="0" C="1" G="0" T="0"/>
					<pos i="21" A="0" C="0.846154" G="0" T="0.153846"/>
					<pos i="22" A="0" C="1" G="0" T="0"/>
					<pos i="23" A="0.076923" C="0.461538" G="0.307692" T="0.153846"/>
					<pos i="24" A="1" C="0" G="0" T="0"/>
					<pos i="25" A="0.230769" C="0" G="0" T="0.769231"/>
					<pos i="26" A="0" C="0" G="0" T="1"/>
					<pos i="27" A="0" C="1" G="0" T="0"/>
					<pos i="28" A="0" C="0.923077" G="0" T="0.076923"/>
					<pos i="29" A="0" C="1" G="0" T="0"/>
				</motif>
				<match target="t_1_2" orientation="forward" offset="0" pvalue="1.55229e-40" evalue="1.39706e-39" qvalue="2.79412e-39"/>
				<match target="t_1_3" orientation="reverse" offset="7" pvalue="2.42149e-17" evalue="2.17934e-16" qvalue="2.17934e-16"/>
			</query>
			<query>
				<motif id="q_3" name="3" length="40" nsites="11" evalue="9.2e-050" >
					<pos i="1" A="0.545455" C="0.181818" G="0.181818" T="0.090909"/>
					<pos i="2" A="0.090909" C="0" G="0.909091" T="0"/>
					<pos i="3" A="0" C="0.909091" G="0.090909" T="0"/>
					<pos i="4" A="0.181818" C="0.454545" G="0.272727" T="0.090909"/>
					<pos i="5" A="0.090909" C="0" G="0.909091" T="0"/>
					<pos i="6" A="0.090909" C="0.090909" G="0.727273" T="0.090909"/>
					<pos i="7" A="0.090909" C="0" G="0.909091" T="0"/>
					<pos i="8" A="1" C="0" G="0" T="0"/>
					<pos i="9" A="0.636364" C="0" G="0.181818" T="0.181818"/>
					<pos i="10" A="0" C="0" G="0" T="1"/>
					<pos i="11" A="0.181818" C="0.636364" G="0.181818" T="0"/>
					<pos i="12" A="0" C="0" G="1" T="0"/>
					<pos i="13" A="0.272727" C="0" G="0.636364" T="0.090909"/>
					<pos i="14" A="0" C="0" G="0.909091" T="0.090909"/>
					<pos i="15" A="1" C="0" G="0" T="0"/>
					<pos i="16" A="0.636364" C="0.090909" G="0.090909" T="0.181818"/>
					<pos i="17" A="0" C="0" G="0" T="1"/>
					<pos i="18" A="0.090909" C="0.727273" G="0.181818" T="0"/>
					<pos i="19" A="0.090909" C="0" G="0.909091" T="0"/>
					<pos i="20" A="0.272727" C="0" G="0.727273" T="0"/>
					<pos i="21" A="0" C="0" G="1" T="0"/>
					<pos i="22" A="1" C="0" G="0" T="0"/>
					<pos i="23" A="0.272727" C="0.181818" G="0.090909" T="0.454545"/>
					<pos i="24" A="0" C="0" G="0" T="1"/>
					<pos i="25" A="0.090909" C="0.545455" G="0.181818" T="0.181818"/>
					<pos i="26" A="0.090909" C="0" G="0.909091" T="0"/>
					<pos i="27" A="0.090909" C="0" G="0.909091" T="0"/>
					<pos i="28" A="0" C="0" G="1" T="0"/>
					<pos i="29" A="1" C="0" G="0" T="0"/>
					<pos i="30" A="0.636364" C="0" G="0" T="0.363636"/>
					<pos i="31" A="0" C="0" G="0" T="1"/>
					<pos i="32" A="0" C="0.545455" G="0.272727" T="0.181818"/>
					<pos i="33" A="0" C="0" G="1" T="0"/>
					<pos i="34" A="0" C="0.545455" G="0.090909" T="0.363636"/>
					<pos i="35" A="0.636364" C="0.181818" G="0" T="0.181818"/>
					<pos i="36" A="0.818182" C="0.090909" G="0.090909" T="0"/>
					<pos i="37" A="0.363636" C="0.545455" G="0.090909" T="0"/>
					<pos i="38" A="0.727273" C="0.090909" G="0.090909" T="0.090909"/>
					<pos i="39" A="0.090909" C="0.181818" G="0.636364" T="0.090909"/>
					<pos i="40" A="0" C="0.818182" G="0.090909" T="0.090909"/>
				</motif>
				<match target="t_1_3" orientation="forward" offset="0" pvalue="0" evalue="0" qvalue="0"/>
				<match target="t_1_2" orientation="reverse" offset="-4" pvalue="6.26731e-18" evalue="5.64058e-17" qvalue="5.64058e-17"/>
			</query>
			<query>
				<motif id="q_4" name="4" length="41" nsites="145" evalue="3.1e-064" >
					<pos i="1" A="0.324138" C="0.206897" G="0.213793" T="0.255172"/>
					<pos i="2" A="0" C="0.57931" G="0.413793" T="0.006897"/>
					<pos i="3" A="0.337931" C="0.02069" G="0.489655" T="0.151724"/>
					<pos i="4" A="0.262069" C="0.234483" G="0.151724" T="0.351724"/>
					<pos i="5" A="0" C="0.496552" G="0.482759" T="0.02069"/>